### ISSUE TITLE
NoMethodError: undefined method `api_only' for #<Rails::Application::Configuration:...> in Rails 3.2

### ISSUE THREAD

**Issue by igrep** [rails/jbuilder#269]
Seems https://github.com/rails/jbuilder/commit/29c0014a9c954c990075d42c45c66075260e924b makes it incompatible with environment without Rails API.

Here is the stack trace:

```
NoMethodError: undefined method `api_only' for #<Rails::Application::Configuration:0x007f0c25445678>
vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/railtie/configuration.rb:85:in `method_missing'
vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/core_ext/object/try.rb:36:in `try'
vendor/bundle/ruby/2.1.0/gems/jbuilder-2.2.14/lib/jbuilder/railtie.rb:12:in `block in <class:Railtie>'
vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
config/environment.rb:5:in `<top (required)>'
vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/application.rb:103:in `require_environment!'
vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
Tasks: TOP => db:migrate:reset => db:migrate => environmentP
```

**Comment by igrep** [comment]
Oh, sorry. Duplicate with https://github.com/rails/jbuilder/issues/268 .
I'll close.

**Comment by rwz** [comment]
Well, shit. I actually thought I've fixed it here: https://github.com/rails/jbuilder/commit/09b36f837563f8bb61f275721d7c672e399f27f4

Turns out I didn't.

**Comment by igrep** [comment]
Yeah, as you might know, I found `try` in Rails 3.x doesn't ask `respond_to?` to the receiver.
So https://github.com/rails/jbuilder/commit/09b36f837563f8bb61f275721d7c672e399f27f4 doesn't fix.
http://apidock.com/rails/v3.2.13/Object/try

**Comment by rwz** [comment]
Fixed in 2.2.15. Sorry about that :(
